chore(workflow): update release workflow to allow minor releases (#2695)
### What does this PR do?

When doing a minor release, we get this error, example, doing a `1.14.1`
release:

```sh
Switched to a new branch 'bump-to-1.15.0'
You asked to amend the most recent commit, but doing so would make
On branch bump-to-1.15.0
No changes
it empty. You can repeat your command with --allow-empty, or you can
remove the commit entirely with "git reset HEAD^".
Error: Process completed with exit code 1.
```

It tries to create a PR to update the version even if it's already on
the next major version.

This update allows us to do minor versions fine.

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

<!-- Include any related issues from Podman Desktop
repository (or from another issue tracker). -->

N/A, discovered during the release process.

### How to test this PR?

N/A

Signed-off-by: Charlie Drage <charlie@charliedrage.com>