chore(ci): add qemu static to enable building arm64
### What does this PR do?

In our workflow, we are missing the qemu static binary which is causing
issues building ARM64 on CI:

```sh
STEP 1/8: FROM registry.access.redhat.com/ubi10/nodejs-22-minimal:10.1-1764649415
Trying to pull registry.access.redhat.com/ubi10/nodejs-22-minimal:10.1-1764649415...
Getting image source signatures
Copying blob sha256:d1309107f4fddbcacf869ab8f3ae992a3db5bcadfc1bc0352fda34bd8cea1c57
Copying blob sha256:9c27140b3e778c26a038c982eb0b0d7c55918358b1c1e3afdb013d53d318ad1f
Copying config sha256:d4b7333b4aef45169320451a3f6a6691f70c936de61752bc2b65e65fb8670583
Writing manifest to image destination
STEP 2/8: ENV HOME=/opt/app-root
STEP 3/8: WORKDIR /opt/app-root/extension-source
STEP 4/8: RUN mkdir -p /opt/app-root/extension-source
exec container process `/bin/sh`: Exec format error
Error: building at STEP "RUN mkdir -p /opt/app-root/extension-source": while running runtime: exit status 1
Error: Error: buildah exited with code 1
Trying to pull registry.access.redhat.com/ubi10/nodejs-22-minimal:10.1-1764649415...
Getting image source signatures
Copying blob sha256:d1309107f4fddbcacf869ab8f3ae992a3db5bcadfc1bc0352fda34bd8cea1c57
Copying blob sha256:9c27140b3e778c26a038c982eb0b0d7c55918358b1c1e3afdb013d53d318ad1f
Copying config sha256:d4b7333b4aef45169320451a3f6a6691f70c936de61752bc2b65e65fb8670583
Writing manifest to image destination
exec container process `/bin/sh`: Exec format error
Error: building at STEP "RUN mkdir -p /opt/app-root/extension-source": while running runtime: exit status 1
```

Specifically the `Exec format error` issue.

### Screenshot / video of UI

<!-- If this PR is changing UI, please include
screenshots or screencasts showing the difference -->

N/A

### What issues does this PR fix or reference?

<!-- Include any related issues from Podman Desktop
repository (or from another issue tracker). -->

Part of https://github.com/podman-desktop/extension-bootc/issues/2101

### How to test this PR?

<!-- Please explain steps to reproduce -->

Merge and CI (should) pass :)

Signed-off-by: Charlie Drage <charlie@charliedrage.com>